config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/users' => 'users#index'
  post'/users' => 'users#create'
  get '/users/new' => 'users#new'
  get '/users/:id' => 'users#show', as: :user
  patch '/users/:id' => 'users#update'
  get '/users/edit/:id' => 'users#edit', as: :user_edit
  get '/users/edit/:id/password' => 'users#change_password', as: :user_password_edit
  get '/users/destroy/:id' => 'users#destroy', as: :user_remove

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy', as: :log_out

  get '/blog' => 'posts#index'
  post '/blog' => 'posts#create', as: :posts
  get '/blog/new' => 'posts#new'
  get '/blog/:slug' => 'posts#show', as: :post
  patch '/blog/:slug' => 'posts#update'
  get '/blog/:slug/edit' => 'posts#edit', as: :post_edit

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  before_create :create_slug, :assign_creator
  before_update :assign_updator
  attr_reader :created_by

  field :title, type: String
  field :body, type: String
  field :slug, type: String
  field :created_by, type: String
  field :updated_by, type: String

  validates_presence_of :title

  belongs_to :user

  def create_slug
    self.slug = self.title.downcase.gsub(/\s/, '-').gsub(/[^0-9A-Za-z\-]/, '')
  end

  def assign_creator
    self.created_by = self.user_id
  end

  def assign_updator
    self.updated_by = self.user_id
  end

end

app/models/role.rb
class Role
  include Mongoid::Document
  field :name, type: String
  field :_id, type: String, default: ->{ name }

  has_many :users
end

app/models/user.rb
class User
  include Mongoid::Document
  before_create :encrypt_password
  before_update :needs_password?
  attr_accessor :password, :old_password

  field :email, type: String
  field :password_hash, type: String
  field :password_salt, type: String

  validates_confirmation_of :password
  validates_presence_of :password, on: :create

  belongs_to :role
  has_many :posts

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def needs_password?
    unless password && old_password
      if User.authenticate(email, old_password)
        encrypt_password
      end
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :is_admin?, :is_me?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user != nil
  end

  def require_login
    unless logged_in?
      redirect_to log_in_path
    end
  end

  def is_admin?
    current_user.role_id == 'Administrator'
  end  

  def require_admin
    unless is_admin?
      redirect_to log_in_path
    end
  end

  def is_me? user = nil
    unless user.nil?
      user.id == current_user.id
    else
      current_user.id.to_s == params[:id]
    end
  end

  def require_privilege
    unless is_me? || is_admin?
      redirect_to users_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new, :edit]
  def index
    @posts = Post.all.desc(:created_at)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  def show
    @post = Post.find_by(slug: params[:slug])
  end

  def edit
    @post = Post.find_by(slug: params[:slug])
    unless is_author? || is_admin?
      redirect_to root_path
    end
  end

  def update
    @post = Post.find(params[:slug])
    @post.update_attributes(post_params)
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end

    def is_author?
      @current_user.id == @post.created_by
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if logged_in?
  end
  
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id.to_s
      redirect_to root_path
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:index, :new, :edit, :change_password, :show]
  before_action :require_admin, only: [:new, :destroy]
  before_action :require_privilege, only: [:edit, :change_password]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to root_path
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def change_password
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to root_path
  end

  def destroy
    User.find(params[:id]).remove

    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :old_password, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def posted_on post
    (post.created_at).strftime('%B %d, %Y')
  end

  def in_path? str
    /#{str}/.match request.env['PATH_INFO']
  end
end

app/views/home/index.slim
div class="root-wrap"
  h1 This is the 'Home' page.

  p Don't forget to run 'rails g mongoid:config

app/views/layouts/application.slim
doctype html
html
  head
    title ScratchAuth
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    - if logged_in?
      = render 'shared/navbar'

    div class="container"
      div class="page-wrap"
        header
          = render 'shared/header'

        main
          = yield

app/views/posts/_form.slim
= form_for @post do |f|
  = f.hidden_field :user_id, value: @current_user.id.to_s
  
  p
    => f.label :title
    = f.text_field :title

  p
    = f.label :body
  p
    = f.text_area :body, class: "tinymce", cols: 72, rows: 15

  p
    = f.submit "Create Post"

= tinymce

app/views/posts/edit.slim
h1
  |Edit Post

= render 'form'

app/views/posts/index.slim
div class="latest"
  h2 class="title"
    = @posts.first.title

  p class="date"
    = posted_on @posts.first

  div class="latest-body"
    = @posts.first.body.html_safe

div class="other-posts"
  h3 Older Posts 
  - @posts.each do |p|
    - unless p == @posts.first
      p
        => link_to p.title, post_path(p.slug)
        = "- #{posted_on p}"

app/views/posts/new.slim
h1
  |New Post

= render 'form'

app/views/posts/show.slim
div class="post"
  h2 class="title"
    = @post.title

  p class="date"
    = posted_on @post

  p
    = @post.body.html_safe

app/views/shared/_header.slim
h1 class="logo" App Name

app/views/shared/_navbar.slim
div class="navbar navbar-inverse"
  div class="container"
    p class="navbar-text navbar-left"
      = "Signed in as #{current_user.email}"
    
    div class="navbar-right"
      ul class="nav navbar-nav"
        li
          = link_to 'New post', blog_new_path
        li
          = link_to 'Users', users_path
      = link_to "Log Out", log_out_path, class: "btn btn-default navbar-btn"

app/views/shared/_sidebar.slim
small Placeholder...

app/views/users/change_password.slim
h1
  |Change password for #{@user.email}

= form_for @user do |f|
  p
    => f.label :email
    = f.text_field :email, disabled: true

  p
    => f.label :old_password
    = f.password_field :old_password

  p
    => f.label :password
    = f.password_field :password

  p
    => f.label :password_confirmation
    = f.password_field :password_confirmation

  p
    = f.submit 'Change password'

app/views/users/edit.slim
h1
  |Edit user #{@user.email}

= form_for @user do |f|
  p
    => f.label :email
    = f.text_field :email

  p
    => f.label :role_id
    = f.collection_select :role_id, Role.all, :id, :name if is_admin?
    = f.text_field :role_id, disabled: true unless is_admin?
  p
    = f.submit "Update user"

p
  = link_to 'Change Password', user_password_edit_path(@user.id)

app/views/users/index.slim
h2 Users

table class="table table-striped"
  - @users.each do |u|
    tr
      td
        = link_to u.email, user_path(u.id)
      td
        = u.role_id
      
      -if (is_admin? or is_me? u)
        td  
          = link_to 'Edit', user_edit_path(u.id)
      - if is_admin?
        td
          = link_to 'Remove', user_remove_path(u.id) , data: { confirm: 'Are you sure?' }

app/views/users/new.slim
h1
  |Sign Up

= form_for @user do |f|
  p
    => f.label :email
    = f.text_field :email

  p
    => f.label :role_id
    = f.collection_select :role_id, Role.all, :id, :name

  p
    => f.label :password
    =  f.password_field :password

  p
    => f.label :password_confirmation
    = f.password_field :password_confirmation

  p
    = f.submit "Sign Up"

app/views/users/show.slim
h1
  = @user.email